### PR TITLE
Converted to Kotlin and updated

### PR DESCRIPTION
**Pull request by Doomsdayrs**
- Kotlin conversion
- Ran through android lint
- fixed for loops with foreach and maps
- Removed redundant XML and strings

### CODE REVIEW

**Comment by alvitawa** [comment]
Hey! Thanks, it is nice to have someone look at the code.

I'm going to test it out on my end and see if anything broke. However, I am unsure what the usefulness of this conversion is. Given the nature of this application, I think the most important consideration for language choice is accessibility, so that anyone can hack in something if they need to for a (custom) physical device. Java seems very suited for this purpose, however, Kotlin could still be more accessible if the app can be expressed more naturally in it. Looking at the generated code, I am not convinced that the code is clearer in Kotlin.

Do you think it is possible to clean up the code so that it is not only written in Kotlin, but clearly benefits from it as well? Otherwise, I am not sure the change is worth it.

Also, why Kotlin, compared to the other jvm languages?

**Comment by Doomsdayrs** [comment]
- Kotlin is a language that is officially supported by Android, with numerous benefits that can be caught up on kotlins own [documentation](https://kotlinlang.org/docs/reference/comparison-to-java.html). Kotlin is also newer, and like all nice things open source

- I only did an initial conversion of Java to Kotlin, with a few loops being converted as well. Example below
```kotlin
var mDevices: Set<BluetoothDevice>? = null
		set(value) {
			field = value
			field?.let { devices ->
				mNames.clear()
				mAddresses.clear()
				devices.forEach {
					mNames.add(it.name)
					mAddresses.add(it.address)
				}
			}
		}
```
In java, you had to keep track of incidences, and more. Kotlin allows a single expression to handle all changes

The reason the code doesn't look cleaner, as this is a dirty conversion. But there are places that are far cleaner with conversion. Boiler plate code is far less in Kotlin the java. 

For example in `HomeActivity`, (the one on your current master), you have 14 lines of variable initialization, then 14 more lines to initialize each view. Totaling 28 lines of code that clunk of how you view things. 

This is not all, In the previous example with mDevices, you can see an expression 
`field?.let { devices -> ... }`
This expression reads, If variable `field` is not null, let `devices` = not null, then execute the `...`. Otherwise if is null, don't execute
This is cleaner then `if (field!=null) { ... }`, it does have the same effective of building up, but one of Kotlins points is being null safe.

**Comment by Doomsdayrs** [comment]
```kotlin
fun Context.toast(message: String, length: Int = Toast.LENGTH_LONG) =
		Toast.makeText(this, message, length)!!
```
Also extension functions, that allow you to extend functionality of libraries with your own methods. AND default values for function parameters

**Comment by Doomsdayrs** [comment]
From BluetoothSerialActivityBase, This is the bloat you get with checks for nulls
```java
        // Show or hide the "Connect" and "Disconnect" buttons on the app bar
        if (bluetoothSerial.isConnected()) {
            if (actionConnect != null)
                actionConnect.setVisible(false);
            if (actionDisconnect != null)
                actionDisconnect.setVisible(true);
        } else {
            if (actionConnect != null)
                actionConnect.setVisible(true);
            if (actionDisconnect != null)
                actionDisconnect.setVisible(false);
        }
```
Here is the kotlin fix
```kotlin
	bluetoothSerial?.let { bS ->
		actionConnect?.let { it.isVisible = !bS.isConnected }
		actionDisconnect?.let { it.isVisible = bS.isConnected }
	}
```
In many kotlin expressions `it` refers to whatever the expression is applied to. In these cases, the two its refer to, respectfully, actionConnect & actionDisconnect

**Comment by Doomsdayrs** [comment]
Smaller things do build up
```java
    @Override
    public void onConnectingBluetoothDevice() {
        updateBluetoothState();
    }
```
to 
```kotlin
    override fun onConnectingBluetoothDevice() = updateBluetoothState()
```

**Comment by Doomsdayrs** [comment]
In `BluetoothDeviceListDialog`
You use an interface for a single method
```java

    /**
     * Listener for the {@link com.macroyau.blue2serial.BluetoothDeviceListDialog}.
     */
    public interface OnDeviceSelectedListener {

        /**
         * A remote Bluetooth device is selected from the dialog.
         *
         * @param device The selected device.
         */
        void onBluetoothDeviceSelected(BluetoothDevice device);

    }
```
```kotlin
	private var onDeviceSelectedListener: (device: BluetoothDevice?) -> Unit = {}
```
Converting into an expression, single function interfaces are clunky

**Comment by Doomsdayrs** [comment]
```kotlin
inline fun <reified T : Any> T.logID() = T::class.java.simpleName
``` 
Importing this as an extension, Pretty much gets a logID for each class by it's compiled class name

**Comment by Doomsdayrs** [comment]
Your last commit: 1589 lines
My commits: 1268 lines

300~ lines of code less to read

Can confirm lots of brackets and if statements

**Comment by alvitawa** [comment]
Thanks for the examples.  Even though I have not written Kotlin before, it does seem to be the nicer language based on the examples you give and the general trend in online discussions. However, as you said, this is a dirty conversion, so I am hesitant to add it as-is, on the grounds that if anyone were to have to look at this code it would be less readable.

An example is:
`val address = parts[1].trim { it <= ' ' }.toInt()`
vs
`int address = Integer.parseInt(parts[1].trim());`

From an online search it is clear that the additional parameters given to trim in the Kotlin version are necessary to keep the behavior identical, but, in this case, this is probably not necessary.

> one of Kotlin's points is being null safe.

It is only null safe if used as such, I see a lot of double bangs (`!!`) in the code, which, if I understand correctly, will raise a `NullpointerException` just the same as the original java.

So, I don't want to merge it unless it is looked at by a human first, so it is indeed Kotlin and not Java-Kotlin (Javalin?).

Also note that a lot of the improvements you mention are part of the Blue2Serial library (which is 4 years old and I did not write, but it 'just works'). I don't expect to touch this code unless it is to fix bugs. In retrospect, it would have been better to add this as an external dependency rather than a source library. I may still want to do this in the future. So changes to this component may be better suited to the original Blue2Serial repo (https://github.com/MacroYau/Blue2Serial).

Relevant code for this project (that I wrote) is in the `/app` folder.

**Comment by alvitawa** [comment]
Maybe we can add Blue2Serial as an external dependency, and then convert the project to Kotlin. But this is not something I can work on any time soon.

**Comment by Doomsdayrs** [comment]
Wait, If Blue 2 serial is a dependencey, why is it imported in code, instead of as a dependency

**Comment by Doomsdayrs** [comment]
Oh. Oh my. What did you even do

**Comment by alvitawa** [comment]
Next time you do this it might be a good idea to check in with the maintainer to see if a conversion to Kotlin is a good idea at all, or in what form it would be usefull.

**Pull request closed without merging**
